//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public int queue_id { get; set; }
        public Nullable<int> counter_id { get; set; }
        public string queue_number { get; set; }
        public string status { get; set; }
        public string name { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_completed { get; set; }
    
        public virtual Counter Counter { get; set; }
    }
}
